# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: BSD-2-Clause

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/windows.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/flatpak.yml
